<a href="https://colab.research.google.com/github/04-disha-shetty/Workshop-on-Python-Programmin-in-DA-and-ML/blob/master/Day3_Session2_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas


# Write a Pandas program to convert a Panda module Series to Python list and its type.

In [1]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


# Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [2]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# Write a Pandas program to compare the elements of the two Pandas Series.

In [3]:
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


# Write a Pandas program to convert a dictionary to a Pandas series.

In [4]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


# Write a Pandas program to convert a NumPy array to a Pandas series.

In [5]:
pip install numpy

In [6]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


# Write a Pandas program to change the data type of the given Series into numeric

In [7]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


# Write a Pandas program to convert a given Series to an array.

In [8]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


# Write a Pandas program to sort a given Series.

In [9]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


# Write a Pandas program to add some data to an existing Series.

In [10]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


# Write a Pandas program to create a subset of a given series based on value and condition.

In [11]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


# Write a Pandas program to change the order of index of a given series.

In [12]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


# Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series

In [14]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


# Write a Pandas program to get the elements of an array values into column-wise.

In [15]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


# Write a NumPy program to generate five random numbers from the normal distribution.

In [25]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[ 0.48475205  1.31582597  1.56619983  0.29973103 -0.89396412]


# Write a NumPy program to generate six random integers between 10 and 30

In [26]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[16 12 22 20 27 29]


# Write a NumPy program to create a 3x3x3 array with random values

In [28]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.3902742  0.01329469 0.53295459]
  [0.94328236 0.52595741 0.1991321 ]
  [0.33005665 0.89535834 0.53705505]]

 [[0.87710511 0.62286407 0.53700225]
  [0.18102603 0.68183313 0.69024907]
  [0.32523369 0.11292557 0.23001673]]

 [[0.83177825 0.13437873 0.28769356]
  [0.70058598 0.11058505 0.20754624]
  [0.40437255 0.73462359 0.53128207]]]


# Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [29]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.0114856  0.4808531  0.69238741 0.75467787 0.45537287]
 [0.26549872 0.1409144  0.35666494 0.550872   0.9337694 ]
 [0.45901589 0.41000003 0.14461722 0.97769452 0.03128798]
 [0.92370887 0.45280546 0.08447354 0.14417321 0.07556445]
 [0.88854025 0.60529528 0.75608443 0.41103851 0.15363352]]
Minimum and Maximum Values:
0.01148560307731361 0.9776945170536294


# Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.

In [30]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.98869352 0.47675978 0.26356369 0.52965565]
 [0.05364918 0.85255545 0.0744408  0.95529642]
 [0.45529437 0.79412247 0.3707567  0.41460606]
 [0.46766991 0.66363492 0.70240131 0.39031799]
 [0.83825337 0.65956215 0.75761563 0.94927379]
 [0.0766971  0.93982309 0.16690126 0.48280849]
 [0.06693563 0.65570884 0.03156412 0.73317412]
 [0.74037314 0.08496727 0.25244012 0.23714669]
 [0.59579871 0.75260102 0.37720736 0.9855301 ]
 [0.62487121 0.59442856 0.34429888 0.53366377]]
First 5 rows of the above array:
[[0.98869352 0.47675978 0.26356369 0.52965565]
 [0.05364918 0.85255545 0.0744408  0.95529642]
 [0.45529437 0.79412247 0.3707567  0.41460606]
 [0.46766991 0.66363492 0.70240131 0.39031799]
 [0.83825337 0.65956215 0.75761563 0.94927379]]
First 3 columns of the above array:
[[0.98869352 0.47675978 0.26356369 0.52965565]
 [0.05364918 0.85255545 0.0744408  0.95529642]
 [0.45529437 0.79412247 0.3707567  0.41460606]
 [0.46766991 0.66363492 0.70240131 0.39031799]
 [0.83825337 0.6595

# Write a NumPy program to shuffle numbers and find permutation between 0 and 10 #(inclusive).

In [31]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[7 0 5 9 1 8 4 6 2 3]
Same result using permutation():
[2 4 9 8 3 1 7 0 6 5]


# Write a NumPy program to create a random integer nos of size 10 and sort it.

In [32]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.21286761 0.90185933 0.35746292 0.55629363 0.98202162 0.13560324
 0.57288253 0.02603781 0.78008931 0.37147082]
Sorted array:
[0.02603781 0.13560324 0.21286761 0.35746292 0.37147082 0.55629363
 0.57288253 0.78008931 0.90185933 0.98202162]


# Write a NumPy program to create a random integer nos of size 10 and sort it.

In [33]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[0 9 5 8 3 4 6 1 2 7]
[0 1 2 3 4 5 6 7 8 9]
