<a href="https://colab.research.google.com/github/04-disha-shetty/Workshop-on-Python-Programmin-in-DA-and-ML/blob/master/Day3_Session2_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000

In [1]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


# Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [2]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


# Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [3]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.

In [4]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


# Write a Pandas program to convert a NumPy array to a Pandas series.

In [5]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


# Write a Pandas program to convert a given Series to an array.

In [6]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


# Write a Pandas program to sort a given Series.

In [7]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


# Write a Pandas program to create a subsets of a given series based on value and condition.

In [8]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


# Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [9]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


# Write a Pandas program to get the elements of an array values into column-wise.

In [10]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


# Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [11]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


# Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [12]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x)

Original Array:
[[0.66267068 0.77567311 0.31815108 0.15937307]
 [0.1320235  0.54556466 0.1128068  0.60504341]
 [0.49197794 0.1216144  0.97898132 0.02519152]
 [0.49743065 0.05471789 0.37562924 0.31317488]]


# Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [13]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.43046649 0.94652076 0.52975012 0.61908168 0.4524775  0.12229929
  0.0536864  0.8096917  0.59862365 0.73534346]
 [0.73081668 0.78837313 0.15821329 0.72391352 0.74144584 0.46249295
  0.42962769 0.77650874 0.1710201  0.61990948]
 [0.79212205 0.10232451 0.78875806 0.18758401 0.93658964 0.33113131
  0.36580469 0.97363218 0.37355992 0.52063882]
 [0.23772766 0.65176225 0.34011493 0.73360716 0.98176931 0.28364811
  0.14097092 0.80726978 0.59868215 0.45869725]
 [0.41957613 0.80175565 0.49703463 0.19777526 0.2952522  0.61997206
  0.1273041  0.46352682 0.86732973 0.37039636]
 [0.98554338 0.42613302 0.40007263 0.70488528 0.17314571 0.5222234
  0.02918439 0.18694743 0.4146518  0.837913  ]
 [0.6036268  0.15934531 0.61864949 0.30073412 0.68207691 0.82829905
  0.17950503 0.70456516 0.52879625 0.69885254]
 [0.44420541 0.72998805 0.06378968 0.53625758 0.09695434 0.42855971
  0.69147712 0.73084018 0.74039477 0.04006133]
 [0.23298902 0.68455162 0.71790045 0.16623915 0.66060059 0.722446

# Write a NumPy program to generate 8 random integers between 100 and 300

In [14]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[118 159 185 290 270 227 141 184]


# Write a NumPy program to create a random integer nos of size 20 and sort it.

In [15]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.68159672 0.23752421 0.80224123 0.57670369 0.93094168 0.42924218
 0.95967434 0.43460531 0.8646726  0.37214274 0.09723014 0.65764095
 0.93115615 0.86069047 0.84750486 0.47312758 0.71780902 0.4205127
 0.57954444 0.65426984]
Sorted array:
[0.09723014 0.23752421 0.37214274 0.4205127  0.42924218 0.43460531
 0.47312758 0.57670369 0.57954444 0.65426984 0.65764095 0.68159672
 0.71780902 0.80224123 0.84750486 0.86069047 0.8646726  0.93094168
 0.93115615 0.95967434]
